### ISSUE TITLE
exporter file format  as same as  the built-in log export file

### ISSUE THREAD

**Issue by dengfan2018** [nccgroup/LoggerPlusPlus#191] opened 2023-08-28 02:43 UTC
**Feature description:**
I want using the export files with "sqlmap  -l  **.log".

 the built-in log export file can use with sqlmap,  LoggerPlusPlus export files  cannot use with sqlmap

**Scenario example:**

**Comment by C0DEbrained** [comment] 2023-10-26 10:00
Duplicate of #133

**Closed as completed by C0DEbrained** 2023-10-26 10:00 UTC
Labels: enhancement
