### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jonaslejon** [nccgroup/LoggerPlusPlus#100] opened 2020-05-23 09:34 UTC
**Description:**
Can't start Logger++ in Burp. The menu is showing but it is not possible to click on the menu bar Logger++.

```
java.lang.NullPointerException
	at com.nccgroup.loggerplusplus.LoggerContextMenuFactory.createMenuItems(LoggerContextMenuFactory.java:35)
	at burp.a9i.a(Unknown Source)
	at burp.flh.a(Unknown Source)
	at burp.dq_.a(Unknown Source)
	at burp.dq_.a(Unknown Source)
	at burp.aud.a(Unknown Source)
	at burp.aud.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6586)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4540)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at com.nccgroup.loggerplusplus.LoggerContextMenuFactory.createMenuItems(LoggerContextMenuFactory.java:35)
	at burp.a9i.a(Unknown Source)
	at burp.flh.a(Unknown Source)
	at burp.dq_.a(Unknown Source)
	at burp.dq_.a(Unknown Source)
	at burp.aud.a(Unknown Source)
	at burp.aud.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6586)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4540)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at com.nccgroup.loggerplusplus.LoggerContextMenuFactory.createMenuItems(LoggerContextMenuFactory.java:35)
	at burp.a9i.a(Unknown Source)
	at burp.flh.a(Unknown Source)
	at burp.d4l.a(Unknown Source)
	at burp.bio.a(Unknown Source)
	at burp.bgp.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6586)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4540)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Steps To Reproduce:**
I'm running Burp Suite on macOS with the following command:
`java -jar burpsuite_pro_v2020.4.1.jar`

**Expected behavior:**

**Screenshots:**

**Version:**
3.18

**Comment by CoreyD97** [comment] 2020-05-23 10:13
Thanks for raising this. Looking at the stack trace, the error occurs when Burp tries to register the context menu. However, that shouldn't really happen until a request has been right clicked such as in the Repeater panel so up until that point I'd expect Logger to load and function normally. 

Is there any particular steps to reproduce this? Or does it just happen any time you attempt to load it up?

**Comment by jonaslejon** [comment] 2020-05-24 14:36
I managed to get Logger++ working again by disabling all the other extensions. So it seems to be related to some conflict between other plugin.

Attached is a screenshot with all the plugins i'm running.

<img width="391" alt="Skärmavbild 2020-05-24 kl  16 35 32" src="https://user-images.githubusercontent.com/190150/82756802-b5ff6100-9ddc-11ea-95ef-b65bd861424c.png">

**Comment by jonaslejon** [comment] 2020-05-26 19:40
The issue seems to be related to the GadgetProbe extension: https://portswigger.net/bappstore/e20cad259d73403bba5ac4e393a8583f

When enabling it Logger++ stops working.

**Comment by CoreyD97** [comment] 2020-05-26 19:44
Interesting... Thanks for figuring this out. I'll look into it. Very strange behaviour indeed!

**Comment by CoreyD97** [comment] 2020-05-27 22:33
I've attempted to reproduce this but can't seem to trigger any unexpected behaviour. I tried different load orders, triggering a reload of the extensions and a couple of other things. I didn't spot anything odd in the GadgetProbe extension that could interfere either.

Is there something in particular that triggers this? Or just simply trying to load both extensions?

**Comment by Klambyyy** [comment] 2020-06-03 12:26
I also get this problem with the latest version of Logger++. Though I noticed if I install the 3.17 release from GitHub I could actually use the extension. On 3.18 it wouldn't work at all and the visual elements were a bit screwed up).

My terminal Burp log when using latest L++:
[log.txt](https://github.com/nccgroup/LoggerPlusPlus/files/4723194/log.txt)

After rolling back to 3.17
[log2.txt](https://github.com/nccgroup/LoggerPlusPlus/files/4723206/log2.txt)

I'm on Linux Mint, using:
`$ java -jar burpsuite_pro_v2020.4.jar`
Current extensions:
![image](https://user-images.githubusercontent.com/48349801/83636285-99fa7d00-a59d-11ea-9ae3-9f7f5c4ed09c.png)

**Comment by CoreyD97** [comment] 2020-06-03 13:53
Thanks for the logs Klambyyy, they're very helpful.
The issue you're seeing in log.txt seems to be unrelated to this particular issue, so I've created a new issue for that as well.

**Comment by P0desta** [comment] 2020-06-21 08:16
Hello, I want to ask if this problem has been solved? I also encountered the same problem, logger++ cannot be used normally because of java.lang.NullPointerException.

**Comment by CoreyD97** [comment] 2020-06-21 08:32
Hi @P0desta, I'm having trouble reproducing this issue. Is there any chance you can share your stack trace also please?

**Comment by P0desta** [comment] 2020-06-21 08:34
Hello @CoreyD97 
```
java.lang.NullPointerException
	at javax.swing.DefaultRowSorter.convertRowIndexToModel(DefaultRowSorter.java:518)
	at javax.swing.JTable.convertRowIndexToModel(JTable.java:2645)
	at javax.swing.JTable.getValueAt(JTable.java:2720)
	at javax.swing.JTable.prepareRenderer(JTable.java:5712)
	at com.nccgroup.loggerplusplus.logview.logtable.LogTable.prepareRenderer(LogTable.java:116)
	at javax.swing.plaf.synth.SynthTableUI.paintCell(SynthTableUI.java:683)
	at javax.swing.plaf.synth.SynthTableUI.paintCells(SynthTableUI.java:580)
	at javax.swing.plaf.synth.SynthTableUI.paint(SynthTableUI.java:364)
	at javax.swing.plaf.synth.SynthTableUI.update(SynthTableUI.java:275)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by CoreyD97** [comment] 2020-06-21 08:37
Thanks, I'll take a look at that this week 😁

**Comment by jonaslejon** [comment] 2020-06-24 09:07
When I changed from the jar to running the macOS release form Burp Suite it started working again.

**Comment by CoreyD97** [comment] 2020-06-24 09:29
Odd, thanks for the heads up!
Could you tell me which jar version you were using by any chance? :)

**Comment by JulianVolodia** [comment] 2020-10-21 18:53
@jonaslejon any chance to know if:
- any of that problems raised again?
- which versions was that?

Have a great day!

**Comment by CoreyD97** [comment] 2021-01-26 09:00
I believe both these issues should be fixed with the latest releases available from this repo and the upcoming release. 

If you're still receiving any of these errors using these versions, please let me know and we can reopen this issue.

**Closed by CoreyD97** 2021-01-26 09:00 UTC
Labels: bug

**Comment by leechboy11** [comment] 2024-08-24 14:02
Hi, I also encountered the same problem.
When the "**json web tokens**" extension is active, filter++ cannot receive the response and gives the same error.
![image](https://github.com/user-attachments/assets/186056ec-8152-42ed-a4a5-41f98af5d966)
![image](https://github.com/user-attachments/assets/637a0c44-f899-450a-a42a-bbe004f12e09)
