### ISSUE TITLE
[Question] Restore logs after Burp closes

### ISSUE THREAD

**Issue by ioasdjiojqiwojaosncasoidjqoiwjeon** [nccgroup/LoggerPlusPlus#148] opened 2022-03-06 16:11 UTC
Is there a way to restore all logs in Logger++ after Burp is closed? I know that I can import the logs from the Burp's Proxy History, the thing is that I want to have an exact copy of the last logs captured by Logger++ which includes logs from Repeater,Intruder,Extender,etc.

**Comment by AkikoOrenji** [comment] 2022-03-21 23:57
See https://github.com/nccgroup/LoggerPlusPlus/issues/133

**Comment by CoreyD97** [comment] 2022-03-23 11:55
Duplicate of #133

**Closed by CoreyD97** 2022-03-23 11:55 UTC
