### ISSUE TITLE
Exporting to ElasticSearch

### ISSUE THREAD

**Issue by henshin** [nccgroup/LoggerPlusPlus#98] opened 2020-05-13 10:56 UTC
**Description:**
Exporting to ElasticSearch doesn't seem to be working on the latest version. 

**Steps To Reproduce:**
Configured Elastic Exporter (refer to the screenshot below).
Note: There's also a weird GUI bug when writing to the index textbox. 
Started the Elastic Exporter
Made some requests on the repeater
Requests are logged on the LoggerPlusPlus but not sent to Elastic 

**Expected behavior:**
After making a few requests, I expected to see the index count increase but it doesn't so no data is being pushed to Elastic.

**Screenshots:**
![Screenshot-2005131149-00262](https://user-images.githubusercontent.com/7304307/81803783-0f7bac00-9510-11ea-90b9-ce4e744335c0.png)
![Screenshot-2005131153-00264](https://user-images.githubusercontent.com/7304307/81804032-6a150800-9510-11ea-913d-0df0f5c96996.png)
![Screenshot-2005131149-00263](https://user-images.githubusercontent.com/7304307/81803780-0ee31580-9510-11ea-8632-fe4905cf8e3d.png)
**Version:**
* BurpSuite Pro 2020.2.1
* LoggerPlusPlus 3.18
* ElasticSearch 6.8.8

**Comment by CoreyD97** [comment] 2020-05-13 11:38
Hey, thanks for raising this.
I was told about this yesterday by somebody on Twitter. Apparently it seems to be caused by selecting the URL field in the column selection. Could you try deselecting that and letting me know if it works afterwards?

Thanks

**Comment by henshin** [comment] 2020-05-13 12:04
Thanks for the quick reply. I tried to unselect the URL field but it still doesn't work. I also tried to unselect most of the other columns but it didn't help either. Let me know if is there anything else you would like me to try.

**Comment by CoreyD97** [comment] 2020-05-13 12:12
Thanks for trying that, I've got a day set aside to work on this tomorrow, so should have it fixed by the end of the day!

**Comment by CoreyD97** [comment] 2020-05-14 08:35
Looks like when I implemented this I was reading the docs for elasticsearch 7, which has removed the need for types in an index. However previous versions still require them.

I'll implement the types now, I imagine these will simply be ignored on elasticsearch 7, but will allow it to work with elasticsearch 6 in the meantime.

**Comment by knodesec** [comment] 2020-05-14 08:45
I am also experiencing this issue, it seems to be when Request.URL is selected, it does not send any logs through to elasticsearch.

All other options selected and the logs appear OK. 

I am running ES7 with the following docker-compose file.

[el7-kibana-compose.txt](https://github.com/nccgroup/LoggerPlusPlus/files/4627041/el7-kibana-compose.txt)

**Comment by CoreyD97** [comment] 2020-05-14 09:34
Turns out this was two separate issues, URL parameter could not be serialized by the json builder, and that elasticsearch 6 requires a type parameter for index requests.

Commit bae7dbf should fix both and will be included in a new release soon.

**Closed** 2020-05-14 09:34 UTC
Labels: bug

**Comment by knodesec** [comment] 2020-05-14 09:38
Awesome, thanks Corey. I don't have a build environment so will wait for a release!

**Comment by CoreyD97** [comment] 2020-05-14 10:44
The repo is setup to use github actions to automatically build releases after every master branch commit, so you can download it from here in the meantime if you wish!

https://github.com/nccgroup/LoggerPlusPlus/actions/runs/104489756

**Comment by knodesec** [comment] 2020-05-14 11:05
Tested and can confirm it seems to be working, with one caveat, in that it can't be used with an index created in a previous version. For future reference, the error is:
  
    ```Rejecting mapping update to [zzz] as the final mapping would have more than 1 type: [_doc, doc]```

Many thanks Corey!

**Comment by henshin** [comment] 2020-05-14 12:44
Also working for me with the latest build.
Thanks for the support!

**Comment by Regala** [comment] 2020-05-20 13:55
@CoreyD97 thanks for this work, I was going crazy trying to debug this issue! 

One question I see that when the extension is loaded the configuration is correctly loaded; but it's not started. Would it be possible to auto-start it (or have a button to check that)?

Cheers!

**Comment by CoreyD97** [comment] 2020-05-20 14:26
Sure, if you want to create a feature request here, I'll add it to my todo list!
Thanks!

**Comment by Regala** [comment] 2020-05-20 15:27
Awesome! Logged it over at #99. Cheers!
